### PR TITLE
Yousra/databases/week1

### PR DESCRIPTION
**Pull request by YousraElmag**

### CODE REVIEW

**Comment by rafaelhdr** [comment]
Nice job. It is working really great. Exercise 2 is perfect, but there is just one adjustment that I would like to suggest.

We can run it fine if the tables already exist, but if we drop the tables first (`DROP TABLES IF EXISTS Invitee, Meeting, Room, employees;`) and then run your script (`node cdb.js`) we have this error:

```
$ node cdb.js
Connected to the database as ID 29
Error inserting data into employees: Error: Table 'meetup.employees' doesn't exist
    at Packet.asError (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/rafaelhdr/hyf/yousra/Week1/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
Employees table created successfully.
Room table created successfully.
Meeting table created successfully.
```

The reason is because `connection.query(createEmployeesTable, (err, results) => {` is running after `connection.query(insertEmployees, (err, results) => {`. That is happening because of the behavior of JS asynchronous tasks.

Try to fix it making the queries run in proper sequence. A tip would be use `queries.forEach((query) => executeQuery(query, connection));`, that will run query by query.

**Comment by YousraElmag** [comment]
thanks for review i fixed error

**Comment by rafaelhdr** [comment]
You were so fast.

You did great. It is working good.

**Comment by YousraElmag** [comment]
Thank you very much

**Pull request closed without merging**
