### PR TITLE
Yousra/database/Week3

### PR DESCRIPTION
**Pull request by YousraElmag**

### CODE REVIEW

**Comment by rafaelhdr** [comment]
Exercises 1, 2 and 3 are really good. Congratulations :clap: 

Exercise 4 needs more information. It's a tiny detail that helps a lot. Ref this part:

> We have set up the .gitignore file and provided you with an .env.example file that gives an example of what you .env file should look like.

It is missing the `.env.example` file for us. There is an example in `homework/mongodb/.env.example`, but it doesn't match your index file (the example defines `MONGODB_URL`, but your file is using `DB_URI`, `DB_NAME`...)

**Comment by YousraElmag** [comment]
Thank you for reviewing my code. I didn't use .env.example because I thought I should create a separate .env file

**Comment by YousraElmag** [comment]
Screenshot 2024-08-24 at 15 55 09

**Comment by rafaelhdr** [comment]
> Thank you for reviewing my code. I didn't use .env.example because I thought I should create a separate .env file

That is correct, but I meant `.env.example`. It is a different file.

The `.env.example` has not real data but the correct keys that we need to run. In your case, it could be something like this:

```
DB_URI=mongodb+srv://DB_USERNAME:DB_PASSWORD@DB_HOST/?retryWrites=true&w=majority&appName=Cluster0
DB_NAME=databaseWeek3
```

I can copy it to `.env` and replace the fields `DB_USERNAME`, `DB_PASSWORD` and `DB_HOST`

**Comment by YousraElmag** [comment]
Yes, I did it as an example and updated the index file.

**Comment by YousraElmag** [comment]
Screenshot 2024-08-24 at 22 07 17

**Comment by YousraElmag** [comment]
Screenshot 2024-08-24 at 22 12 20

**Comment by rafaelhdr** [comment]
I think I am not being clear in the conversation here about the `.env.example`. Let's try to discuss in Slack. It might be easier.

**Comment by rafaelhdr** [comment]
> I think I am not being clear in the conversation here about the `.env.example`. Let's try to discuss in Slack. It might be easier.

Actually, yousra was right. I was checking in the wrong place. I will review it again.

**Comment by rafaelhdr** [comment]
And congratulations. It is working very good. You got the idea of the .env :clap:

**Comment by YousraElmag** [comment]
Thank you very much for your effort and honesty in conveying the information.

**Pull request closed without merging**
